output_dir: ~/scratch/aaai24_output

dataset:
  class: PROTACTargets
  path: ~/scratch/protein-datasets/
  atom_feature: null
  bond_feature: null
  transform:
    class: Compose
    transforms:
      - class: ProteinView
        view: residue

task:
  class: GetEmbedding
  model:
    class: FusionNetwork
    sequence_model:
      class: ESM
      path: ~/scratch/protein-model-weights/esm-model-weights/
      model: ESM-2-650M
    structure_model:
      class: GearNet
      input_dim: 1280
      hidden_dims: [512, 512, 512, 512, 512, 512]
      batch_norm: True
      concat_hidden: True
      short_cut: True
      readout: 'sum'
      num_relation: 7
  graph_construction_model:
    class: GraphConstruction
    node_layers:
      - class: AlphaCarbonNode
    edge_layers:
      - class: SequentialEdge
        max_distance: 2
      - class: SpatialEdge
        radius: 10.0
        min_distance: 5
      - class: KNNEdge
        k: 10
        min_distance: 5


optimizer:
  class: Adam
  lr: 1.0e-4

engine:
  gpus: [0, 1, 2]
  batch_size: 1
  log_interval: 1000

model_checkpoint: ~/scratch/pretrained_models/mc_esm_gearnet.pth

sequence_model_lr_ratio: 0.1

# metric: f1_max

# train:
#   num_epoch: 50